apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-hpipe-sa
  labels:
    app: {{ .Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: {{ .Release.Name }}-hpipe-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-hpipe-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-hpipe-sa
  namespace: {{ .Release.Namespace }} 
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-hpipe-role
  apiGroup: rbac.authorization.k8s.io

